/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef userProfileServices_CONSTANTS_H
#define userProfileServices_CONSTANTS_H

#include "userProfileServices_types.h"



class userProfileServicesConstants {
 public:
  userProfileServicesConstants();

};

extern const userProfileServicesConstants g_userProfileServices_constants;



#endif
