/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "userProfileServices_constants.h"



const userProfileServicesConstants g_userProfileServices_constants;

userProfileServicesConstants::userProfileServicesConstants() {
}



